namespace HannibalUI.Editor.CodeGen
{
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Emits the <c>CanvasType</c> and <c>UIEvents</c> enums (as C# source strings) from a
    /// <see cref="UIProjectConfig"/>. These files are generator-owned and overwritten each run.
    /// File I/O lives in the generation orchestrator, not here, so this stays unit-testable.
    /// </summary>
    public static class EnumGenerator
    {
        private const string RuntimeNamespace = "HannibalUI.Runtime.Base";

        public static string GenerateCanvasType(UIProjectConfig config)
        {
            var members = new List<string>();

            foreach (var screen in config.Screens)
            {
                members.Add(IdentifierUtility.ToPascalCase(screen.Name));
            }

            members.Add("Count"); // sentinel — must stay last; used as the canvases array size.

            return BuildEnum("CanvasType", members);
        }

        public static string GenerateUIEvents(UIProjectConfig config)
        {
            var members = new List<string> { "NONE" };

            foreach (var transition in config.Transitions)
            {
                members.Add(IdentifierUtility.ToValidIdentifier(transition.EventName));
            }

            return BuildEnum("UIEvents", members);
        }

        private static string BuildEnum(string enumName, IEnumerable<string> members)
        {
            var ordered = DistinctPreservingOrder(members);

            var sb = new StringBuilder();
            sb.Append(AutoGeneratedHeader());
            sb.Append("namespace ").Append(RuntimeNamespace).Append('\n');
            sb.Append("{\n");
            sb.Append("    public enum ").Append(enumName).Append('\n');
            sb.Append("    {\n");

            for (int i = 0; i < ordered.Count; i++)
            {
                var comma = i < ordered.Count - 1 ? "," : string.Empty;
                sb.Append("        ").Append(ordered[i]).Append(comma).Append('\n');
            }

            sb.Append("    }\n");
            sb.Append("}\n");

            return sb.ToString();
        }

        private static List<string> DistinctPreservingOrder(IEnumerable<string> members)
        {
            var seen = new HashSet<string>();
            var ordered = new List<string>();

            foreach (var member in members)
            {
                if (seen.Add(member))
                {
                    ordered.Add(member);
                }
            }

            return ordered;
        }

        private static string AutoGeneratedHeader()
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated>\n");
            sb.Append("//     Generated by HannibalUI from a UIProjectConfig asset.\n");
            sb.Append("//     Manual edits are overwritten on the next generate.\n");
            sb.Append("// </auto-generated>\n");
            return sb.ToString();
        }
    }
}
