namespace HannibalUI.Editor.CodeGen
{
    using System.Text;
    using HannibalUI.Runtime.Base;

    /// <summary>
    /// Emits a <c>VP_Director</c> subclass that supplies the navigation routes and start screen
    /// from the config, so the director needs no Inspector wiring. Generator-owned (overwritten).
    /// </summary>
    public static class RouteGenerator
    {
        private const string GeneratedNamespace = "HannibalUI.Runtime.Generated";
        private const string DirectorClassName = "VP_GeneratedDirector";

        public static string GenerateDirector(UIProjectConfig config)
        {
            var startMember = StartScreenMember(config);

            var sb = new StringBuilder();
            sb.Append(AutoGeneratedHeader());
            sb.Append("namespace ").Append(GeneratedNamespace).Append('\n');
            sb.Append("{\n");
            sb.Append("    using System.Collections.Generic;\n");
            sb.Append("    using HannibalUI.Runtime.Base;\n");
            sb.Append('\n');
            sb.Append("    public class ").Append(DirectorClassName).Append(" : VP_Director\n");
            sb.Append("    {\n");
            sb.Append("        protected override CanvasType StartScreen => ")
              .Append(startMember == null ? "default" : "CanvasType." + startMember)
              .Append(";\n");
            sb.Append('\n');
            sb.Append("        protected override IReadOnlyList<NavRoute> GetRoutes()\n");
            sb.Append("        {\n");
            sb.Append("            return new NavRoute[]\n");
            sb.Append("            {\n");

            foreach (var transition in config.Transitions)
            {
                var eventMember = IdentifierUtility.ToValidIdentifier(transition.EventName);
                var target = TargetExpression(transition);

                sb.Append("                new NavRoute { Event = UIEvents.")
                  .Append(eventMember)
                  .Append(", Action = NavActionType.")
                  .Append(transition.Action.ToString())
                  .Append(", Target = ")
                  .Append(target)
                  .Append(" },\n");
            }

            sb.Append("            };\n");
            sb.Append("        }\n");
            sb.Append("    }\n");
            sb.Append("}\n");

            return sb.ToString();
        }

        private static string TargetExpression(TransitionDefinition transition)
        {
            bool needsTarget = transition.Action == NavActionType.Show || transition.Action == NavActionType.Push;

            if (needsTarget && !string.IsNullOrWhiteSpace(transition.TargetScreen))
            {
                return "CanvasType." + IdentifierUtility.ToPascalCase(transition.TargetScreen);
            }

            return "default"; // Pop/Back ignore Target.
        }

        private static string StartScreenMember(UIProjectConfig config)
        {
            ScreenDefinition start = null;

            foreach (var screen in config.Screens)
            {
                if (screen.IsPopup)
                {
                    continue;
                }

                if (screen.IsStart)
                {
                    start = screen;
                    break;
                }

                start ??= screen; // fall back to the first non-popup screen.
            }

            return start == null ? null : IdentifierUtility.ToPascalCase(start.Name);
        }

        private static string AutoGeneratedHeader()
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated>\n");
            sb.Append("//     Generated by HannibalUI from a UIProjectConfig asset.\n");
            sb.Append("//     Manual edits are overwritten on the next generate.\n");
            sb.Append("// </auto-generated>\n");
            return sb.ToString();
        }
    }
}
